"""Unit tests for the RAG answer generators, with a fake LangChain chat model."""

from langchain_core.language_models.fake_chat_models import FakeMessagesListChatModel
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

from legal_workflow_generator.rag.generator import NO_CONTEXT_ANSWER, AnswerGenerator

CHUNKS = [{"provision_id": "posh_act_2013_sec_4", "title": "Internal Committee", "text": "Every employer shall..."}]


class RecordingChatModel(FakeMessagesListChatModel):
    calls: list = []

    def invoke(self, messages, *args, **kwargs):
        self.calls.append(messages)
        return super().invoke(messages, *args, **kwargs)


def test_generate_sends_system_and_context_messages():
    llm = RecordingChatModel(responses=[AIMessage(content="Yes, constitute an IC.")], calls=[])
    answer = AnswerGenerator(llm).generate("Do I need a POSH committee?", CHUNKS)

    assert answer == "Yes, constitute an IC."
    assert type(answer) is str
    system, user = llm.calls[0]
    assert isinstance(system, SystemMessage) and "ONLY the retrieved legal context" in system.content
    assert isinstance(user, HumanMessage)
    assert "posh_act_2013_sec_4" in user.content and "Do I need a POSH committee?" in user.content


def test_generate_without_chunks_skips_llm():
    llm = RecordingChatModel(responses=[AIMessage(content="unused")], calls=[])
    assert AnswerGenerator(llm).generate("q", []) == NO_CONTEXT_ANSWER
    assert llm.calls == []


def test_empty_response_falls_back():
    llm = RecordingChatModel(responses=[AIMessage(content="")], calls=[])
    assert AnswerGenerator(llm).generate("q", CHUNKS) == "No response generated by LLM model."
