from typing import Any

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage

from legal_workflow_generator.llm import chat_model, groq_chat_model

SYSTEM_PROMPT = """You are a legal workflow assistant for Indian tech startups.

Answer the user query using ONLY the retrieved legal context below.
If the context is insufficient, clearly say what is missing.
Do not invent sections, obligations, penalties, or dates.
Keep the answer practical and concise for a startup founder.

Output format:
1) Short answer (2-5 bullet points)
2) Action checklist (if query asks process/compliance)
3) Sources (cite provision_id + title from context)
4) Add this line at end: "This is informational guidance, not legal advice."
"""

NO_CONTEXT_ANSWER = (
    "I could not find relevant legal provisions for your query. "
    "Please rephrase with more details (law name, compliance step, or section topic)."
)


class AnswerGenerator:
    """
    Generates a grounded legal answer using retrieved law chunks.

    Notes:
    - This module is for informational use in a startup compliance assistant.
    - It is grounded strictly in retrieved provisions.
    """

    provider = "LLM"

    def __init__(self, llm: BaseChatModel):
        self.llm = llm

    def generate(self, query: str, retrieved_chunks: list[dict[str, Any]]) -> str:
        if not retrieved_chunks:
            return NO_CONTEXT_ANSWER

        user_prompt = f"User query:\n{query}\n\nRetrieved legal context:\n{self._format_context(retrieved_chunks)}"
        response = self.llm.invoke([SystemMessage(content=SYSTEM_PROMPT), HumanMessage(content=user_prompt)])
        return str(response.text) or f"No response generated by {self.provider} model."

    @staticmethod
    def _format_context(retrieved_chunks: list[dict[str, Any]]) -> str:
        context_blocks = []
        for i, chunk in enumerate(retrieved_chunks, start=1):
            summary = chunk.get("plain_english_summary") or ""
            text = chunk.get("text") or ""
            snippet = summary if summary else text

            # keep prompt compact while preserving grounding quality
            if len(snippet) > 1200:
                snippet = snippet[:1200] + "..."

            context_blocks.append(
                "\n".join(
                    [
                        f"[{i}] provision_id: {chunk.get('provision_id', '')}",
                        f"[{i}] statute_id: {chunk.get('statute_id', '')}",
                        f"[{i}] section_number: {chunk.get('number', '')}",
                        f"[{i}] title: {chunk.get('title', '')}",
                        f"[{i}] content: {snippet}",
                    ]
                )
            )
        return "\n\n".join(context_blocks)


class GeminiAnswerGenerator(AnswerGenerator):
    provider = "Gemini"

    def __init__(self):
        super().__init__(chat_model())


class GroqAnswerGenerator(AnswerGenerator):
    provider = "Groq"

    def __init__(self):
        # Temperature 0 is ideal for RAG to prevent hallucinations
        super().__init__(groq_chat_model(temperature=0.0))
