from typing import Any

from google import genai
from groq import Groq

from legal_workflow_generator.config.values import GEMINI_API_KEY, GEMINI_MODEL
from legal_workflow_generator.config.values import GROQ_API_KEY, GROQ_MODEL


class GeminiAnswerGenerator:
    """
    Generates a grounded legal answer using retrieved law chunks.

    Notes:
    - This module is for informational use in a startup compliance assistant.
    - It is grounded strictly in retrieved provisions.
    """

    def __init__(self, model_name: str = GEMINI_MODEL):
        if not GEMINI_API_KEY:
            raise ValueError("GEMINI_API_KEY is not set in environment")

        self.client = genai.Client(api_key=GEMINI_API_KEY)
        self.model_name = model_name

    def generate(self, query: str, retrieved_chunks: list[dict[str, Any]]) -> str:
        if not retrieved_chunks:
            return (
                "I could not find relevant legal provisions for your query. "
                "Please rephrase with more details (law name, compliance step, or section topic)."
            )

        context_blocks = []
        for i, chunk in enumerate(retrieved_chunks, start=1):
            summary = chunk.get("plain_english_summary") or ""
            text = chunk.get("text") or ""
            snippet = summary if summary else text

            # keep prompt compact while preserving grounding quality
            if len(snippet) > 1200:
                snippet = snippet[:1200] + "..."

            context_blocks.append(
                "\n".join(
                    [
                        f"[{i}] provision_id: {chunk.get('provision_id', '')}",
                        f"[{i}] statute_id: {chunk.get('statute_id', '')}",
                        f"[{i}] section_number: {chunk.get('number', '')}",
                        f"[{i}] title: {chunk.get('title', '')}",
                        f"[{i}] content: {snippet}",
                    ]
                )
            )

        context_text = "\n\n".join(context_blocks)

        prompt = f"""
You are a legal workflow assistant for Indian tech startups.

Answer the user query using ONLY the retrieved legal context below.
If the context is insufficient, clearly say what is missing.
Do not invent sections, obligations, penalties, or dates.
Keep the answer practical and concise for a startup founder.

Output format:
1) Short answer (2-5 bullet points)
2) Action checklist (if query asks process/compliance)
3) Sources (cite provision_id + title from context)
4) Add this line at end: "This is informational guidance, not legal advice."

User query:
{query}

Retrieved legal context:
{context_text}
""".strip()

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt,
        )

        return response.text or "No response generated by Gemini model."



class GroqAnswerGenerator:
    """
    Generates a grounded legal answer using retrieved law chunks.

    Notes:
    - This module is for informational use in a startup compliance assistant.
    - It is grounded strictly in retrieved provisions.
    """

    def __init__(self, model_name: str = GROQ_MODEL):
        if not GROQ_API_KEY:
            raise ValueError("GROQ_API_KEY is not set in environment")

        self.client = Groq(api_key=GROQ_API_KEY)
        self.model_name = model_name

    def generate(self, query: str, retrieved_chunks: list[dict[str, Any]]) -> str:
        if not retrieved_chunks:
            return (
                "I could not find relevant legal provisions for your query. "
                "Please rephrase with more details (law name, compliance step, or section topic)."
            )

        context_blocks = []
        for i, chunk in enumerate(retrieved_chunks, start=1):
            summary = chunk.get("plain_english_summary") or ""
            text = chunk.get("text") or ""
            snippet = summary if summary else text

            # keep prompt compact while preserving grounding quality
            if len(snippet) > 1200:
                snippet = snippet[:1200] + "..."

            context_blocks.append(
                "\n".join(
                    [
                        f"[{i}] provision_id: {chunk.get('provision_id', '')}",
                        f"[{i}] statute_id: {chunk.get('statute_id', '')}",
                        f"[{i}] section_number: {chunk.get('number', '')}",
                        f"[{i}] title: {chunk.get('title', '')}",
                        f"[{i}] content: {snippet}",
                    ]
                )
            )

        context_text = "\n\n".join(context_blocks)

        system_prompt = """You are a legal workflow assistant for Indian tech startups.

Answer the user query using ONLY the retrieved legal context below.
If the context is insufficient, clearly say what is missing.
Do not invent sections, obligations, penalties, or dates.
Keep the answer practical and concise for a startup founder.

Output format:
1) Short answer (2-5 bullet points)
2) Action checklist (if query asks process/compliance)
3) Sources (cite provision_id + title from context)
4) Add this line at end: "This is informational guidance, not legal advice."
"""

        user_prompt = f"User query:\n{query}\n\nRetrieved legal context:\n{context_text}"

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            # Temperature 0 is ideal for RAG to prevent hallucinations
            temperature=0.0, 
        )

        return response.choices[0].message.content or "No response generated by Groq model."
